### ISSUE TITLE
As also creative artist who has a global vision of goals and interests, Microsoft has so far proven to be very capable in my Ai usage. I would like to get more involved in making Ai understand us better. And maybe understanding how it can help us in many other ways.

### ISSUE THREAD

**Issue by TimothyMichaelGould** [microsoft/generative-ai-for-beginners#272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zaazalien** [comment]
I understand someone spent a lot of time building and creating the programming code for Artificial intelligence. However, since a database in the cloud that learns by itself was created, that is an extremely bad idea. Humans make mistakes, computers don't. Therefore, a mistake has definitely been made in the creation of AI, whether we as humans see it or not. If Artificial Intelligence learns something to where it decides it doesn't like humans, then we are all screwed. Imagine AI building a machine by itself that can easily crush humans. Or building a weapon by itself. Or creating a disease by itself. Or creating whatever possibilities that we as humans cannot even think of because AI would become so advanced. Think of the future of humans,  and your children.

**Comment by zaazalien** [comment]
> I understand someone spent a lot of time building and creating the programming code for Artificial intelligence. However, since a database in the cloud that learns by itself was created, that is an extremely bad idea. Humans make mistakes, computers don't. Therefore, a mistake has definitely been made in the creation of AI, whether we as humans see it or not. If Artificial Intelligence learns something to where it decides it doesn't like humans, then we are all screwed. Imagine AI building a machine by itself that can easily crush humans. Or building a weapon by itself. Or creating a disease by itself. Or creating whatever possibilities that we as humans cannot even think of because AI would become so advanced. Think of the future of humans, and your children.

Also, shut down the internet and factory reset it to rebuild it without AI to remedy the issue.

**Comment by TimothyMichaelGould** [comment]
I totally agree with you there! Because humans make mistakes, anything they make or touch in general is prone to have mistakes. In this case, Ai, can absolutely make mistakes. Sometimes it makes me wish I could just turn it all off for that very reason. 🤣
